
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 5s
scrape_configs:

- job_name: mixnetnode
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - mixnetnode:6543
