{
 "title": "Sysadmin Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Mix Node Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Up Time" }
   ],
   "targets": [
    {
     "expr": "up{job=\"mixnetnode\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Ger Consensus Calls / Min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(katzenpost_incoming_conn_incoming_requests_total{job=\"mixnetnode\", command=\"*commands.GetConsensus\"}[1m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Connections Types / Min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(katzenpost_incoming_conn_incoming_requests_total{job=\"mixnetnode\"}[1m])",
     "legendFormat": "{{job}} {{command}} "
    }
   ]
  },
  {
   "title": "Client Requests / 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(katzenpost_kaetzchen_requests_total{job=\"mixnetnode\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Mixnet Queue Size / Min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(katzenpost_scheduler_mix_queue_size_sum{job=\"mixnetnode\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client Requests / 1 H",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(katzenpost_kaetzchen_requests_total{job=\"mixnetnode\"}[1h])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client's Request Duration / Min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(katzenpost_kaetzchen_requests_duration_seconds_sum{job=\"mixnetnode\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Dropped Packets Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "katzenpost_provider_dropped_packets_total{job=\"mixnetnode\"}"
    }
   ]
  },
  {
   "title": "Epoch Above 80000 Failed PKI Fetch  Provider-0",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Failed Requests" }
   ],
   "targets": [
    {
     "expr": " sum(katzenpost_pki_failed_fetch_pki_docs_per_epoch_total{epoch=~\"^[8-9][0-9]+\", job=\"mixnetnode\"}) by (epoch)",
     "legendFormat": "{{epoch}}"
    }
   ]
  },
  {
   "title": "Provider-0 Requests Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "katzenpost_kaetzchen_requests_total{job=\"mixnetnode\"}"
    }
   ]
  },
  {
   "title": "Outgoing Connections Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "katzenpost_outgoing_conn_outgoing_connections_total{job=\"mixnetnode\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (Need to expose Docker stats)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "{{job}}" },
    {
     "expr": "engine_daemon_engine_memory_bytes"
    }
   ]
  }
 ]
}